version: '3.7'

services:
  app:
    build:
      context: ./resources
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8080:80"
    networks:
      - lumen
    environment:
      WWWUSER: '${WWWUSER}'
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    depends_on:
      - mysql
      - redis

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-lumen:/var/lib/mysql
    networks:
      - lumen

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-lumen:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    networks:
      - lumen


secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt

volumes:
  mysql-lumen:
  redis-lumen:

networks:
  lumen:
    driver: bridge
